#!/usr/bin/env bash
# This script installs an configures nginx 
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '37i error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default
service nginx restart
