#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server
apt-get install haproxy -y
echo -e "\n# frontend\nfrontend myfrontend\n\tbind *:80\n\tdefault_backend myservers" >> /etc/haproxy/haproxy.cfg
echo -e "\n# backend\nbackend myservers\n\tbalance roundrobin\n\tserver server1 100.26.255.65:80\n\tserver server2 35.175.129.41" >> /etc/haproxy/haproxy.cfg

service haproxy restart
