#!/usr/bin/env bash
# script

function delete() {
    rm /var/run/holbertonscript.pid
    exit
}

trap "echo I hate the kill command; delete" SIGTERM
trap "echo Y U no love me?!; delete" SIGINT

echo $$ >> /var/run/holbertonscript.pid
while 'true'; do
    echo To infinity and beyond;
done
