#!/usr/bin/env bash
# Reads the contents of ``/etc/passwd``
file="/etc/passwd"
IFS=':'
while read -r usernme pssword id gid info home commnd; do
	echo "The user $usernme is part of the $gid gang, lives in $home and rides $commnd. $id's place is protected by the passcode $pssword, more info about the user here: $info"
done < $file
