#!/usr/bin/env bash
# Changes the address of localhost to 172.0.0.2 and the address of facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.old
echo "172.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
